version: "3.8"

services:
    mongo:
        image: mongo:6.0
        container_name: mongodb
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: mongou
            MONGO_INITDB_ROOT_PASSWORD: mongop
        volumes:
            - mongo_data:/data/db

volumes:
    mongo_data:
